---
- name: Install autoupdate package.
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Configure unattended upgrades settings.
  ansible.builtin.template:
    src: 52unattended-upgrades-local.j2
    dest: /etc/apt/apt.conf.d/52unattended-upgrades-local
    owner: root
    group: root
    mode: '644'

- name: Enable configured autoupdate timer.
  ansible.builtin.service:
    name: unattended-upgrades.service
    state: started
    enabled: yes
