---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: Set binary path
      ansible.builtin.set_fact:
        nano_path: '{{ (ansible_os_family == "Debian") | ternary("/bin/nano", "/usr/bin/nano") }}'
  tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family | lower == "debian"
    - name: Install safe-to-remove-later package.
      ansible.builtin.package:
        name: nano
        state: present
    - name: Retrieve nano executable.
      ansible.builtin.stat:
        path: '{{ nano_path }}'
      register: nano
    - name: Check nano status.
      ansible.builtin.assert:
        that: nano['stat']['exists']
        fail_msg: "'nano' was not installed."
        success_msg: "'nano' successfully installed."
