---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Retrieve zsh executable.
    ansible.builtin.stat:
      path: /usr/bin/zsh
    register: zsh
  - name: Retrieve nano executable.
    ansible.builtin.stat:
      path: /usr/bin/nano
    register: nano
  - name: Check zsh status.
    ansible.builtin.assert:
      that: zsh['stat']['exists']
      fail_msg: Packages were installed.
      success_msg: Packages successfully installed.
  - name: Check nano status.
    ansible.builtin.assert:
      that: not nano['stat']['exists']
      fail_msg: Packages were not uninstalled.
      success_msg: Packages successfully uninstalled.
